---
- name: required packages
  yum: name={{ item }} state=present
  with_items:
      - iptables
      - iptables-services

- name: Copy iptables Config file
  template: src=iptables dest=/etc/sysconfig/iptables

- name: Ensure iptables is working
  service: name=iptables state=restarted enabled=yes
